expando-global/eve-common

- package-lock.json
- package.json
- src/clients/__tests__/shoptet-client.ts
- src/settings/import-settings-joi-schema.ts
- src/settings/import-settings-model.ts
---
- The intention of the PR **is understood** (via description, UI screenshot or video, etc)
- The code behaves as the author likely intended and the way the code …
> Mall statuses to shoptet mapping

- src/order/order-joi-schema.ts
- src/order/order-model.ts
---
- The intention of the PR **is understood** (via description, UI screenshot or video, etc)
- The code behaves as the author likely intended and the way the code …
> (Add) new pricing fields to order

- src/order/order-joi-schema.ts
- src/order/order-model.ts
Price representation is more generic.
Added ability to represent marketplace commissions.
<br><br>
---
- The intention of the PR **is understood** (via description, …
> change: Made Price more generic add: Marketplace commission

- src/order/order-model.ts
enforcovat requirement na některé fieldy (order.items.lineItemPrice, order.price.total, a možná další)
https://appexpando.atlassian.net/browse/AE-1172
<br />
---
<details>
</details>
<details>
as a whole, improves the maintainability, …
>  change order fields required

- package-lock.json
- package.json
- src/order/order-joi-schema.ts
<br />
---
<details>
</details>
<details> …
> Line item price required joi

- package-lock.json
- package.json
- src/clients/fulfillments-client.ts
- src/clients/order-client.ts
<br />
---
<details>
</details>
<details> …
> (Add) client calls

- package-lock.json
- package.json
- src/clients/shoptet-service-client.ts
<br />
---
<details>
</details>
<details> …
> (Add) create shoptet shipment client call and interfaces

- src/clients/__tests__/order-client.ts
- src/clients/__tests__/shoptet-client.ts
- src/order/order-model.ts
Adding resource `_id` to `ApiOrder` interface. The field **was actually being returned** for the whole time, this is simply an interface change.
⚠️ Will be a new major release due to the possibility of breaking changes to TS builds (will required `_id` everywhere).
<br />
---
<details>
</details>
<details> …
> add: `_id` to ApiOrder model

- package-lock.json
- package.json
- src/clients/shoptet-service-client.ts
<br />
---
<details>
</details>
<details> …
> (Add) get shoptet system endpoints

- package-lock.json
- package.json
- src/clients/shoptet-service-client.ts
<br />
---
<details>
</details>
<details> …
> (Edit) endpoints interface

- src/utils.ts
- src/utils/__tests__/queue-processor.ts
- src/utils/queue-processor.ts
Enhancing usability and adding descriptions.
Removing logic where one process was running processes from queue and making each process responsible for running next one.
Mainly fixing issue with bad awaiting of jobs, where one job could stall the pipeline.
<br />
---
<details>
</details>
<details>
_Instead …
> Queue processor upgrade

- package-lock.json
- package.json
- src/models/marketplace-names.ts
- src/mws/get-marketplace-currency.ts
- src/mws/get-marketplace-host.ts
- src/mws/get-marketplace-id.ts
- src/mws/get-marketplace-name.ts
- src/utils/__tests__/queue-processor.ts
<br />
---
<details>
</details>
<details> …
> (Add) amazon se & tr

- src/bootstrapping/environment.ts
- src/clients/shoptet-service-client.ts
- src/models/marketplace-names.ts
- src/models/marketplace-region.ts
- src/mws/get-marketplace-currency.ts
AE-1405 Filters, enums, etc
<br />
---
<details>
</details>
<details>
- The …
> add: emag PL, HU, RO, BG

- package.json
* **automatically push version number and tag**
when running `npm version` do:
* increase version, (same as before)
* push updated package.json (new)
* push tag (new)
BTW more common scenarios, not needed in our scenario:
docs https://docs.npmjs.com/cli/v6/commands/npm-version
workshop https://github.com/fczbkk/workshop-js-tools/blob/master/npm/publish/package.json
<br />
---
<details>
- The PR contains some contextual description of the submitted feature …
> change: better automatic npm version

- src/clients/__tests__/order-client.ts
- src/clients/__tests__/shoptet-client.ts
- src/models/marketplace-names.ts
- src/order/order-joi-schema.ts
- src/order/order-model.ts
Extending order model.
<br />
---
<details>
</details>
<details>
- The …
> change: extend order model

- .github/pull_request_template.md
reminder to bump version in a github template
there is no easy way to move tags during merge (some cumbersome [action-bumpr](https://github.com/marketplace/actions/bumpr-bump-version-when-merging-pull-request-with-specific-labels) ) so it's necessary to not forget bump after the merge into master
<br />
---
<details>
</details>
<details> …
> add: reminder to bump version in a github template

- src/logging/__tests__/health-reporter.ts
- src/logging/health-reporter.ts
- src/testing/providers.ts
Adding `HealthReporter` component that should be used for reporting business processes' health.
<br />
:warning: TODO Don't forget to **bump version after PR merge** 
* `npm version major` (breaking change) or
* `npm version minor` (feature) or
* `npm version patch` (bugfix)
<br />
---
<details>
</details>
<details> …
> add: Health reporter

- src/clients/pickup-list-client.ts
Adding client for [`PATCH /pickup-lists/{pickupListNumber}`](https://github.com/expando-global/eve/pull/651/files)
<br /><br />
:warning: TODO Don't forget to **bump version after PR merge** 
* `npm version major` (breaking change) or
* `npm version minor` (feature) or
* `npm version patch` (bugfix)
<br />
---
<details>
</details>
<details> …
> add: PickupList client

- src/clients/emag-service-client.ts
- src/testing/providers.ts
:warning: TODO Don't forget to **bump version after PR merge** 
* `npm version major` (breaking change) or
* `npm version minor` (feature) or
* `npm version patch` (bugfix)
<br />
---
<details>
</details>
<details>
as a whole, improves …
> emag service client

- src/mws/get-marketplace-currency.ts
> AE-1700: Add marketplace currency mapping for real_de

- src/order/order-model.ts
:warning: TODO Don't forget to **bump version after PR merge** 
* `npm version major` (breaking change) or
* `npm version minor` (feature) or
* `npm version patch` (bugfix)
<br />
---
<details>
</details>
<details>
as a whole, improves …
> marketplaceSku present in order item detail
